[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "https://t.me/m/T5sJkLqiNzgy"
  status = 301
  force = true

[[redirects]]
  from = "/mpstats"
  to = "https://t.me/m/T5sJkLqiNzgy"
  status = 301
  force = true

[[redirects]]
  from = "/mpstats/*"
  to = "https://t.me/m/T5sJkLqiNzgy"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"